# Generated by Django 3.1.5 on 2021-01-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210111_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='order_number',
            field=models.CharField(default=0, max_length=16, verbose_name='Order number'),
            preserve_default=False,
        ),
    ]
