# Generated by Django 3.1.5 on 2021-01-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_check_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='order_number',
            field=models.CharField(max_length=16, serialize=False, verbose_name='Order number'),
        ),
    ]
