# Generated by Django 3.1.5 on 2021-01-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210111_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
    ]
